### ISSUE TITLE
Add a way to change building keybinds

### ISSUE THREAD

**Issue by BigStronk64** [CultOfJakito/UltraTelephone2#30]
I want to crank 90s because I'm not a pussy and the current binds are ass for doing so

**Comment by wafflethings** [comment]
do not disrespect default binds theyre goated

also this is coming in the next update 🙏🙏

**Comment by zelzmiy** [comment]
already fixed in next update

also, you are a pussy and a default 🙏🙏🙏

**Comment by BigStronk64** [comment]
Footnote: is there anyway to disable the fact you have to pay for levels?

**Comment by wafflethings** [comment]
everything can be disabled in the settings, unless we somehow missed this option

**Comment by BigStronk64** [comment]
what is it called?

**Comment by BigStronk64** [comment]
This mod makes my sigma stick rise

**Comment by wafflethings** [comment]
So sigma 🗿🗿

**Comment by zelzmiy** [comment]
> Footnote: is there anyway to disable the fact you have to pay for levels?

brokie🙏🙏🙏🙏🙏🙏🙏🙏🙏

unfortuneatly this can't be disabled, we'll consider updating this in the next update. for now you can manually unlock all levels in settings, or just give yourself a billion coins

**Comment by Hydraxous** [comment]
> Footnote: is there anyway to disable the fact you have to pay for levels?

![satireimage](https://github.com/CultOfJakito/UltraTelephone2/assets/8602389/d1914072-db6e-4b10-a050-e25fa75e2914)

**Comment by BigStronk64** [comment]
Ohh

**Comment by zelzmiy** [comment]
strokin it

**Comment by Hydraxous** [comment]
<details>
  <summary>Spoiler warning</summary>
It doesn't actually spend your P. If you uninstall the mod youll get it back
  
</details>

**Comment by BigStronk64** [comment]
I don't care dawg I will get like a bajillion dollars and buy all the levels contributing heavily to CultOfJakito funds, thank me later sigmas

**Comment by zelzmiy** [comment]
true, give us your money 🙏
