### ISSUE TITLE
Some chaos effects don't disable until you restart

### ISSUE THREAD

**Issue by TeamDoodz** [CultOfJakito/UltraTelephone2#33]
Disabling certain chaos effects in the configuration won't actually disable their behavior until you restart the level. I don't know exactly which effects have this issue but i have seen this problem with the following:

1. Dancing Window
2. Slab Marksman Only

**Comment by wafflethings** [comment]
just dont disable them then 🙏

**Comment by zelzmiy** [comment]
just play altsman only + tiny window then 🙏🙏🙏 who gaf 🗣️🗣️🗣️

**Comment by TeamDoodz** [comment]
you all are grinches

**Comment by zelzmiy** [comment]
inb4 Close as not planned 🔥🔥🔥

**Comment by Hydraxous** [comment]
erm?

**Comment by zelzmiy** [comment]
Fixed in #40
