### ISSUE TITLE
I FUCKING DOWNLOADED THIS BULLSIT AND IT WORKS(sadly) BUT MY ULTRAKILL KEEPS GETTING SMALL AND BOUNCES AROUND MY SCREEN AND I CAN'T PLAY LIKE THIS I'VE LOOKED EVERYWHERE BUT I CAN'T FUCKING FIND ANYTHING

### ISSUE THREAD

**Issue by Ibimsderingo** [CultOfJakito/UltraTelephone2#44]

**Comment by zelzmiy** [comment]
Disable this in Chaos/Effects
called "Dancing Window"

**Comment by zelzmiy** [comment]
also skill issue bozo 🙏 🙏 🙏 🙏 🙏

**Comment by wafflethings** [comment]
i was very proud of that feature : ( 
smh

**Comment by zelzmiy** [comment]
it's true, waffle laboured day and night, for 40 days to make this, only eating when the sun went down

**Comment by Hydraxous** [comment]
skill ichue

**Comment by wafflethings** [comment]
Fr

**Comment by Ibimsderingo** [comment]
okay okay i get it thanks 😭

**Comment by Ibimsderingo** [comment]
i was like trying to figure this out for 30 minutes

**Comment by Ibimsderingo** [comment]
and went through every single option 10 at a time

**Comment by zelzmiy** [comment]
this is actually a skill issue my guy
