### ISSUE TITLE
Enemies do not move

### ISSUE THREAD

**Issue by Mattiscool11118** [CultOfJakito/UltraTelephone2#45]
Most enemies don't move. They act as if "Blind enemies" are enabled in cheats. However, the sword machine works as normal. I haven't tested other enemies but I can imagine they act similar. There aren't any other mods installed other than those required for the mod to work. I Don't know if it's intended or not lol.

**Comment by zelzmiy** [comment]
it's because the mod is broken 🙏 🙏🙏🙏 hope this helps

**Comment by Mattiscool11118** [comment]
Type shit

**Comment by Mattiscool11118** [comment]
Any fix?

**Comment by zelzmiy** [comment]
time travel into the future when tundra is updated and we've made an update to fix it 🙏🙏🙏🙏 hope this helps (also maybe disable the skibidi toilets)
